build: Print a pretty error when image fails to build
For the following Dockerfile
```
FROM dne
```

We print
```
Step 1/1 : FROM dne
FATAL ERROR: Get help at https://kelda.io/blimp/docs/help/
Image build for web failed. This is likely an error with the Dockerfile, rather than Blimp.
Make sure that the image builds with `docker build`.

The full error was:
pull access denied for dne, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```